services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rewards-squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "5432:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data/db:/var/lib/postgresql/data
  api:
    image: ghcr.io/subspace/blockexplorer-rewards:latest
    environment:
      - DB_NAME=rewards-squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db
  processor:
    image: ghcr.io/subspace/blockexplorer-rewards:latest
    environment:
      - DB_NAME=rewards-squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: ["sqd", "process:prod"]
    depends_on:
      - db
