name: Update container image

on:   
  push:
    branches:
      - main

env:
  PROCESSOR_NAME: ghcr.io/${{ github.repository_owner }}/blockexplorer-processor:latest
  API_SERVER_NAME: ghcr.io/${{ github.repository_owner }}/blockexplorer-api-server:latest
  HEALTH_CHECK_NAME: ghcr.io/${{ github.repository_owner }}/health-check:latest

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Build Health check image
        run: docker build . --file Dockerfile --tag $HEALTH_CHECK_NAME
        working-directory: health-check
      
      - name: Push Health check image
        run: docker push $HEALTH_CHECK_NAME
